name: Ansible Install

on:
  push:
    branches:
      - main

jobs:
  jobs:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        containers: [1, 2]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Echo Today
      run: |
        pip install ansible;
        make run
