name: Ansible Install

on:
  push:
    branches:
      - main

jobs:
  jobs:
    strategy:
      matrix:
        os: ['ubuntu-latest'] #macos-latest
        #      containers: [1]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Run Playbook
      run: |
        pip install ansible;
        make run
